name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.17.2
  image_picker: ^1.2.3
  google_mlkit_text_recognition: ^0.17.1
  fl_chart: ^1.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  # Configuration for Android adaptive icons
  adaptive_icon_background: "assets/ic_launcher.png" # Or a hex color like "#FFFFFF"
  adaptive_icon_foreground: "assets/adaptive-foreground.png"

flutter:
  uses-material-design: true

  # Declare the assets folder to access images inside your app
  assets:
    - assets/